alter table public.business_profiles
add column if not exists has_physical_location boolean default false,
add column if not exists location_mode text,
add column if not exists show_map boolean default false,
add column if not exists latitude numeric,
add column if not exists longitude numeric,
add column if not exists service_at_home boolean default false,
add column if not exists free_estimate boolean default false,
add column if not exists retail_sales boolean default false,
add column if not exists wholesale_sales boolean default false,
add column if not exists delivery_available boolean default false,
add column if not exists authorized_distributor boolean default false,
add column if not exists pet_veterinary_service boolean default false,
add column if not exists pet_grooming boolean default false,
add column if not exists pet_daycare boolean default false,
add column if not exists pet_food_accessories boolean default false,
add column if not exists auto_tow_service boolean default false,
add column if not exists auto_diagnostics boolean default false,
add column if not exists auto_parts boolean default false,
add column if not exists auto_wash_detailing boolean default false;
